### ISSUE TITLE
usacloud load-balancer vip-add でSIGSEGV

### ISSUE THREAD

**Issue by xenophy** [sacloud/usacloud#257]
vip-addを行ったところ下記の様にSIGSEGVが発生します。
0.6.0 (とpre-release版両方) / mac OS Sierra で試しました。
Name or ID 意外に --selector で指定しても同じ結果でした。

パラメータの指定が間違っているのでしょうか？
よろしくお願いいたします。

```
usacloud load-balancer vip-add --vip (IP) --port 80 -y "LB NAME"
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x17b177b]

goroutine 65 [running]:
github.com/sacloud/usacloud/command/funcs.LoadBalancerVipAdd(0x2b59620, 0xc42008b630, 0xc4206b8200, 0x0, 0x0)
	/go/src/github.com/sacloud/usacloud/command/funcs/load_balancer_vip_add.go:20 +0x9b
github.com/sacloud/usacloud/command/cli.init.17.func26.1(0x2b59620, 0xc42008b630, 0xc4206b8200, 0xc42058c620, 0xc4202daa40)
	/go/src/github.com/sacloud/usacloud/command/cli/cli_load_balancer_gen.go:4379 +0x46
created by github.com/sacloud/usacloud/command/cli.init.17.func26
	/go/src/github.com/sacloud/usacloud/command/cli/cli_load_balancer_gen.go:4378 +0xfb2
```

**Comment by yamamoto-febc** [comment]
ご報告ありがとうございます！

手元の環境でも再現することが確認できました。
修正しますので少々お待ちください:bow:

**Comment by yamamoto-febc** [comment]
対応版のリリースを行いました。
https://github.com/sacloud/usacloud/releases/tag/v0.6.1

**Comment by xenophy** [comment]
ありがとうございます!
