### ISSUE TITLE
WASMで--query指定時にpanicする

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/usacloud#816]
WASMで以下のコマンドを実行するとpanicする。

```bash
$ usacloud server list --query "."
```

```console
panic: JavaScript error: not implemented

goroutine 7 [running]:
syscall/js.Value.Call(0x7ff8000100000009, 0x1432030, 0x2c5ae8, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.8/x64/src/syscall/js/js.go:400 +0x34
syscall.Open(0x1038, 0x2, 0x0, 0x0, 0x1143400, 0x0, 0x2c5ac4)
        /opt/hostedtoolcache/go/1.15.8/x64/src/syscall/fs_js.go:106 +0x38
os.openFileNolog(0x1038, 0x2, 0x0, 0x0, 0x1737630, 0x10, 0x10)
        /opt/hostedtoolcache/go/1.15.8/x64/src/os/file_unix.go:200 +0xd
os.OpenFile(0x1038, 0x2, 0x0, 0x0, 0x10, 0x1170108, 0x1737630)
        /opt/hostedtoolcache/go/1.15.8/x64/src/os/file.go:327 +0x3
os.Open(...)
        /opt/hostedtoolcache/go/1.15.8/x64/src/os/file.go:307
io/ioutil.ReadFile(0x1038, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0)
        /opt/hostedtoolcache/go/1.15.8/x64/src/io/ioutil/ioutil.go:53 +0x4
github.com/sacloud/usacloud/pkg/util.BytesFromPathOrContent(0x1038, 0x2, 0x18, 0x1170108, 0x16fa460, 0x0, 0x1146680)
        /home/runner/work/usacloud/usacloud/pkg/util/struct.go:52 +0x5
github.com/sacloud/usacloud/pkg/util.StringFromPathOrContent(...)
        /home/runner/work/usacloud/usacloud/pkg/util/struct.go:35
github.com/sacloud/usacloud/pkg/output.(*jsonOutput).printWithQuery(0x17639f0, 0x1737630, 0x1, 0x1, 0x11310b0, 0x16a5e0)
        /home/runner/work/usacloud/usacloud/pkg/output/json_output.go:96 +0x6
github.com/sacloud/usacloud/pkg/output.(*jsonOutput).Print(0x17639f0, 0x1c928f0, 0x1, 0x1, 0x1, 0x1)
        /home/runner/work/usacloud/usacloud/pkg/output/json_output.go:61 +0xb
github.com/sacloud/usacloud/pkg/cmd/core.(*Command).Run(0x1130fc0, 0x40fe60, 0x1ef55e0, 0x1e2d8c0, 0x146c980, 0x0, 0x4, 0x0, 0x0)
        /home/runner/work/usacloud/usacloud/pkg/cmd/core/command.go:246 +0x16
github.com/sacloud/usacloud/pkg/cmd/core.(*Command).CLICommand.func1.1(0x1eeeb40, 0x1130fc0, 0x40fe60, 0x1ef55e0, 0x1e2d8c0, 0x146c980, 0x0, 0x4)
        /home/runner/work/usacloud/usacloud/pkg/cmd/core/command.go:151 +0x2
created by github.com/sacloud/usacloud/pkg/cmd/core.(*Command).CLICommand.func1
        /home/runner/work/usacloud/usacloud/pkg/cmd/core/command.go:150 +0xb
```

usaconの場合usacloudから`util.StringFromPathOrContent()`を呼ぶとWASM側にimportされている`global.process.cwd()`が呼ばれる。しかし`global.process.cwd()`は未実装であるためGo側に`not implemented`が返される。
本来usacon側で対応すべきだがusacloud側での対応も検討する。

**Comment by yamamoto-febc** [comment]
go 1.16対応 (#818) でjs側で軽微な変更が予定されているためその時に合わせて対応する。

**Comment by yamamoto-febc** [comment]
Usacloud側では対応しない。
